class Dummy {
  static String mission =
      "Our mission is to bridge the gap between blood donors and recipients within our university community, ensuring timely access to life-saving blood donations. Through our mobile app, we aim to cultivate a culture of altruism and solidarity, empowering individuals to contribute to the well-being of others by easily connecting donors with those in need. By fostering a supportive network of blood donors, we strive to save lives, promote health, and build a stronger, more compassionate community within our university.";
  static String bloodInformation1 =
      "দুর্ঘটনায় আহত, ক্যান্সার বা অন্য কোন জটিল রোগে আক্রান্তদের জন্য, অস্ত্রোপচার কিংবা সন্তান প্রসব অথবা থ্যালাসেমিয়ার মতো বিভিন্ন রোগের চিকিৎসায় রক্ত সঞ্চালনের প্রয়োজন হয়।\nতবে বাংলাদেশে জনসংখ্যার তুলনায় রক্তদাতার সংখ্যা এখনো নগণ্য।পরিসংখ্যান অনুযায়ী দেশে বছরে আট থেকে নয় লাখ ব্যাগ রক্তের চাহিদা থাকলেও রক্ত সংগ্রহ হয় ছয় থেকে সাড়ে ছয় লাখ ব্যাগ। ঘাটতি থাকে তিন লাখ ব্যাগের বেশি। এছাড়া সংগ্রহকৃত রক্তের মাত্র ৩০ শতাংশ আসে স্বেচ্ছায় রক্তদাতাদের থেকে। এক ব্যাগ রক্ত দিতে সময় লাগে মাত্র ১০ থেকে ১২ মিনিট। এই অল্প সময়ে চাইলেই একজনের প্রাণ বাঁচানো সম্ভব।";
  static String bloodInformation2 = "স্যার সলিমুল্লাহ মেডিকেল কলেজ বিশ্ববিদ্যালয়ের হেমাটোলজি বিভাগের প্রধান ড. সিরাজুল ইসলাম জানিয়েছেন, ১৮ থেকে ৪৫ বছর বয়সের মধ্যে শারীরিকভাবে সুস্থ নারী ও পুরুষ রক্ত দিতে সক্ষম। এক্ষেত্রে পুরুষের ওজন থাকতে হবে অন্তত ৪৮ কেজি এবং নারীর অন্তত ৪৫ কেজি। এছাড়া রক্তদানের সময় রক্তদাতার তাপমাত্রা ৯৯.৫ ফারেনহাইটের নিচে এবং নাড়ির গতি ৭০ থেকে ৯০ এর মধ্যে এবং রক্তচাপ স্বাভাবিক থাকতে হবে। পুরুষদের ক্ষেত্রে রক্তের হিমোগ্লোবিন প্রতি ডেসিলিটারে ১৫ গ্রাম এবং নারীদের ক্ষেত্রে ১৪ গ্রাম হওয়া দরকার। সাধারণত ৯০ দিন পর পর, অর্থাৎ তিন মাস পর পর রক্ত দেওয়া যাবে। সাধারণত প্রাপ্তবয়স্ক সুস্থ মানুষের শরীরে ৪ থেকে ৬ লিটার পরিমাণ রক্ত থাকে। প্রতিবার ৪৫০ মিলিলিটার রক্ত দেয়া হয়।";
  static String bloodInformation3 = "রক্ত দেয়ার পর কিছুটা মাথা ঘোরাতে পারে। এটা স্বাভাবিক। তবে এ সময় হাঁটাহাঁটি না করে অন্তত এক থেকে দুই ঘণ্টা বিশ্রাম নেয়ার পরামর্শ দিয়েছেন ড. সিরাজুল ইসলাম। রক্তদাতা যদি ঘামতে থাকেন এবং অস্থিরতা হয়, তবে তাকে স্যালাইন খাওয়ানোর পরামর্শ দেন তিনি। রক্ত দেয়ার পর লোহিত রক্তকণিকার মাত্রা স্বাভাবিক অবস্থায় ফিরে যেতে অন্তত এক থেকে দেড় মাস সময় লাগে বলে উল্লেখ করেন ড. সিরাজুল ইসলাম। তিনি বলেন, রক্ত দেয়ার সময় শরীর থেকে রক্তের পাশাপাশি ২৫০-৩০০ মিলিগ্রাম আয়রন কমে যায় তাই তার ক্ষয়পূরণে আয়রন ও প্রোটিনযুক্ত খাবার বেশি বেশি খাওয়ার পরামর্শ দিয়েছেন তিনি।";
  static String bloodInformation4 = "দেশের বিভিন্ন ব্লাডব্যাংকের সঙ্গে কথা বলে জানা যায় নিয়মিত রক্ত দেয়ার কিছু উপকার রয়েছে। \b১. এতে একজন মানুষের জীবন বাঁচানো সম্ভব।\n২. নিয়মিত রক্তদাতাদের ক্যানসারে আক্রান্ত হওয়ার ঝুঁকি কম থাকে।\n৩. বছরে তিনবার রক্ত দিলে শরীরে নতুন লোহিত কণিকা তৈরির হার বেড়ে যায়। এতে অস্থিমজ্জা সক্রিয় থাকে। দ্রুত রক্ত স্বল্পতা পূরণ হয়।\n৪. রক্তে কোলেস্টরেলের মাত্রা কমে যায়, এতে রক্তচাপ নিয়ন্ত্রণে থাকে। ফলে হৃদরোগ ও হার্ট অ্যাটাকের ঝুঁকি অনেকটাই কমে যায়।\n৫. রক্ত দিলে যে ক্যালোরি খরচ হয়, তা ওজন কমানোর ক্ষেত্রে ও রক্তচাপ নিয়ন্ত্রণে গুরুত্বপূর্ণ ভূমিকা রাখে।\n৬. শরীরে হেপাটাইটিস-বি, হেপাটাইটিস-সি, জন্ডিস, ম্যালেরিয়া, সিফিলিস, এইচআইভি বা এইডসের মতো বড় কোন রোগ আছে কি না, সেটি বিনা খরচে জানা যায়।\n৭. রোগ প্রতিরোধ ক্ষমতা বাড়ে।\n৮. রক্তদাতার যদি নিজের কখনো রক্তের প্রয়োজন হয় তাহলে ব্লাড ব্যাংকগুলো তাকে অগ্রাধিকার দিয়ে রক্তের ব্যবস্থা করে দেয়।";
  static String terms1 = "1. Public Disclosure Consent: As a user, you consent to publicly share your personal details such as name, contact number, geographical location, and blood type to aid in blood donation activities.";
  static String terms2 = "2. Liability Disclaimer: The service operators shall not be held accountable for any unauthorized use of your personal information by external parties.";
  static String terms3 = "3. Contact by Others: You acknowledge that you may be approached by unspecified individuals for the purpose of donating blood, and understand that the service operators will not be responsible for any disturbances or damages that may arise from such contact.";
  static String terms4 = "4. Age and Legal Competence Confirmation: You affirm that you are of the age of majority and possess the legal authority to agree to these terms.";
  static String terms5 = "5. Terms Modification Rights: The service administrators maintain the right to alter these terms and conditions at their discretion, without any obligation to provide advance notification.";
  static String terms6 = "";
}
