// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD28kFVqpcrQLlMQlKLGZBrzHPEPRuqccQ',
    appId: '1:678025766607:web:db96fa218f15a9e67079ba',
    messagingSenderId: '678025766607',
    projectId: 'bloodbank-53e7f',
    authDomain: 'bloodbank-53e7f.firebaseapp.com',
    storageBucket: 'bloodbank-53e7f.appspot.com',
    measurementId: 'G-078467R397',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCEzjw4XpierClidKgnt9T6upN__zGlfc',
    appId: '1:678025766607:android:ed096eb5ac0fd4337079ba',
    messagingSenderId: '678025766607',
    projectId: 'bloodbank-53e7f',
    storageBucket: 'bloodbank-53e7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCULcasi0l3hhktNDcsIcqZLO2t0vsMHQw',
    appId: '1:678025766607:ios:97fbcb3966aea5ef7079ba',
    messagingSenderId: '678025766607',
    projectId: 'bloodbank-53e7f',
    storageBucket: 'bloodbank-53e7f.appspot.com',
    iosBundleId: 'com.example.bloodbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCULcasi0l3hhktNDcsIcqZLO2t0vsMHQw',
    appId: '1:678025766607:ios:f6f01b113fed67cc7079ba',
    messagingSenderId: '678025766607',
    projectId: 'bloodbank-53e7f',
    storageBucket: 'bloodbank-53e7f.appspot.com',
    iosBundleId: 'com.example.bloodbank.RunnerTests',
  );
}
